server:
  port: 8088

spring:
  config:
    import: "classpath:authorization-mapping.yml"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9080/realms/OneBank

keycloak:
  auth-server-url: http://localhost:9080
  realm: OneBank
  resource: Order
  credentials:
    secret: dm6KHJExOMU2WEgGHCoP9ZVy3ANvzF3Y
  ssl-required: none
  confidential-port: 0