server:
  port: 8086

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9080/realms/OneBank

keycloak:
  auth-server-url: http://localhost:9080
  realm: OneBank
  resource: ERP-App
  credentials:
    secret: VywnDnjHVTLLm6C7jK7lEPokwraT6ERY
  ssl-required: none
  confidential-port: 0