app:
  security:
    mode: MIXED

server:
  port: 8085

spring:
  config:
    import: "classpath:authorization-mapping.yml"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.10.56:9080/realms/OneBank

keycloak:
  auth-server-url: http://192.168.10.56:9080
  realm: OneBank
  resource: Product
  credentials:
    secret: 3VMMRoeytzGte4ea0pgEfu5vqsqAMYAW
  ssl-required: none
  confidential-port: 0

